---
controller:
  config:
      compute-full-forwarded-for: "true"
      use-forwarded-headers: "true"
      proxy-body-size: "0"
      proxy-read-timeout: "600"
      proxy-send-timeout: "600"
  ingressClassResource:
      name: external-nginx
      enabled: true
      default: false
  affinity:
    podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - ingress-nginx
          topologyKey: kubernetes.io/hostname
  replicaCount: 1 # for production multiple instances
  admissionWaitSeconds:
    enabled: true
  service:
    annotations:
      cloud.google.com/load-balancer-type: External # private ingress = internal
  metrics:
    enabled: true

      
   
